# Generated by Django 4.2 on 2024-04-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_start_at', models.DateTimeField()),
                ('course_students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='api.student')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('grade_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
